// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file idp/cloudaccount/v1/cloud_account.proto (package idp.cloudaccount.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ValidateCredentialsRequest, ValidateCredentialsResponse } from "./cloud_account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service idp.cloudaccount.v1.CloudAccountService
 */
export const CloudAccountService = {
  typeName: "idp.cloudaccount.v1.CloudAccountService",
  methods: {
    /**
     * @generated from rpc idp.cloudaccount.v1.CloudAccountService.ValidateCredentials
     */
    validateCredentials: {
      name: "ValidateCredentials",
      I: ValidateCredentialsRequest,
      O: ValidateCredentialsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

