// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file idp/cloudaccount/v1/cloud_account.proto (package idp.cloudaccount.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file idp/cloudaccount/v1/cloud_account.proto.
 */
export const file_idp_cloudaccount_v1_cloud_account: GenFile = /*@__PURE__*/
  fileDesc("CidpZHAvY2xvdWRhY2NvdW50L3YxL2Nsb3VkX2FjY291bnQucHJvdG8SE2lkcC5jbG91ZGFjY291bnQudjEiSAoaVmFsaWRhdGVDcmVkZW50aWFsc1JlcXVlc3QSGAoQY2xvdWRfYWNjb3VudF9pZBgBIAEoCRIQCghwcm92aWRlchgCIAEoCSJXChtWYWxpZGF0ZUNyZWRlbnRpYWxzUmVzcG9uc2USDQoFdmFsaWQYASABKAgSDQoFZXJyb3IYAiABKAkSGgoSYWNjb3VudF9pZGVudGlmaWVyGAMgASgJMo8BChNDbG91ZEFjY291bnRTZXJ2aWNlEngKE1ZhbGlkYXRlQ3JlZGVudGlhbHMSLy5pZHAuY2xvdWRhY2NvdW50LnYxLlZhbGlkYXRlQ3JlZGVudGlhbHNSZXF1ZXN0GjAuaWRwLmNsb3VkYWNjb3VudC52MS5WYWxpZGF0ZUNyZWRlbnRpYWxzUmVzcG9uc2VCTlpMZ2l0aHViLmNvbS9kcmV3cGF5bWVudC9vcmJpdC9wcm90by9nZW4vZ28vaWRwL2Nsb3VkYWNjb3VudC92MTtjbG91ZGFjY291bnR2MWIGcHJvdG8z");

/**
 * @generated from message idp.cloudaccount.v1.ValidateCredentialsRequest
 */
export type ValidateCredentialsRequest = Message<"idp.cloudaccount.v1.ValidateCredentialsRequest"> & {
  /**
   * @generated from field: string cloud_account_id = 1;
   */
  cloudAccountId: string;

  /**
   * @generated from field: string provider = 2;
   */
  provider: string;
};

/**
 * Describes the message idp.cloudaccount.v1.ValidateCredentialsRequest.
 * Use `create(ValidateCredentialsRequestSchema)` to create a new message.
 */
export const ValidateCredentialsRequestSchema: GenMessage<ValidateCredentialsRequest> = /*@__PURE__*/
  messageDesc(file_idp_cloudaccount_v1_cloud_account, 0);

/**
 * @generated from message idp.cloudaccount.v1.ValidateCredentialsResponse
 */
export type ValidateCredentialsResponse = Message<"idp.cloudaccount.v1.ValidateCredentialsResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;

  /**
   * @generated from field: string account_identifier = 3;
   */
  accountIdentifier: string;
};

/**
 * Describes the message idp.cloudaccount.v1.ValidateCredentialsResponse.
 * Use `create(ValidateCredentialsResponseSchema)` to create a new message.
 */
export const ValidateCredentialsResponseSchema: GenMessage<ValidateCredentialsResponse> = /*@__PURE__*/
  messageDesc(file_idp_cloudaccount_v1_cloud_account, 1);

/**
 * @generated from service idp.cloudaccount.v1.CloudAccountService
 */
export const CloudAccountService: GenService<{
  /**
   * @generated from rpc idp.cloudaccount.v1.CloudAccountService.ValidateCredentials
   */
  validateCredentials: {
    methodKind: "unary";
    input: typeof ValidateCredentialsRequestSchema;
    output: typeof ValidateCredentialsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_idp_cloudaccount_v1_cloud_account, 0);

