// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file idp/health/v1/health.proto (package idp.health.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file idp/health/v1/health.proto.
 */
export const file_idp_health_v1_health: GenFile = /*@__PURE__*/
  fileDesc("ChppZHAvaGVhbHRoL3YxL2hlYWx0aC5wcm90bxINaWRwLmhlYWx0aC52MSJnCgxIZWFsdGhDb25maWcSCwoDdXJsGAEgASgJEg4KBm1ldGhvZBgCIAEoCRIXCg9leHBlY3RlZF9zdGF0dXMYAyABKAUSEAoIaW50ZXJ2YWwYBCABKAUSDwoHdGltZW91dBgFIAEoBSJbChVNYW5hZ2VTY2hlZHVsZVJlcXVlc3QSDgoGYXBwX2lkGAEgASgJEjIKDWhlYWx0aF9jb25maWcYAiABKAsyGy5pZHAuaGVhbHRoLnYxLkhlYWx0aENvbmZpZyJNChZNYW5hZ2VTY2hlZHVsZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSEwoLc2NoZWR1bGVfaWQYAiABKAkSDQoFZXJyb3IYAyABKAkiJwoVRGVsZXRlU2NoZWR1bGVSZXF1ZXN0Eg4KBmFwcF9pZBgBIAEoCSI4ChZEZWxldGVTY2hlZHVsZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDQoFZXJyb3IYAiABKAkyzQEKDUhlYWx0aFNlcnZpY2USXQoOTWFuYWdlU2NoZWR1bGUSJC5pZHAuaGVhbHRoLnYxLk1hbmFnZVNjaGVkdWxlUmVxdWVzdBolLmlkcC5oZWFsdGgudjEuTWFuYWdlU2NoZWR1bGVSZXNwb25zZRJdCg5EZWxldGVTY2hlZHVsZRIkLmlkcC5oZWFsdGgudjEuRGVsZXRlU2NoZWR1bGVSZXF1ZXN0GiUuaWRwLmhlYWx0aC52MS5EZWxldGVTY2hlZHVsZVJlc3BvbnNlQkJaQGdpdGh1Yi5jb20vZHJld3BheW1lbnQvb3JiaXQvcHJvdG8vZ2VuL2dvL2lkcC9oZWFsdGgvdjE7aGVhbHRodjFiBnByb3RvMw");

/**
 * @generated from message idp.health.v1.HealthConfig
 */
export type HealthConfig = Message<"idp.health.v1.HealthConfig"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * @generated from field: int32 expected_status = 3;
   */
  expectedStatus: number;

  /**
   * @generated from field: int32 interval = 4;
   */
  interval: number;

  /**
   * @generated from field: int32 timeout = 5;
   */
  timeout: number;
};

/**
 * Describes the message idp.health.v1.HealthConfig.
 * Use `create(HealthConfigSchema)` to create a new message.
 */
export const HealthConfigSchema: GenMessage<HealthConfig> = /*@__PURE__*/
  messageDesc(file_idp_health_v1_health, 0);

/**
 * @generated from message idp.health.v1.ManageScheduleRequest
 */
export type ManageScheduleRequest = Message<"idp.health.v1.ManageScheduleRequest"> & {
  /**
   * @generated from field: string app_id = 1;
   */
  appId: string;

  /**
   * @generated from field: idp.health.v1.HealthConfig health_config = 2;
   */
  healthConfig?: HealthConfig;
};

/**
 * Describes the message idp.health.v1.ManageScheduleRequest.
 * Use `create(ManageScheduleRequestSchema)` to create a new message.
 */
export const ManageScheduleRequestSchema: GenMessage<ManageScheduleRequest> = /*@__PURE__*/
  messageDesc(file_idp_health_v1_health, 1);

/**
 * @generated from message idp.health.v1.ManageScheduleResponse
 */
export type ManageScheduleResponse = Message<"idp.health.v1.ManageScheduleResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string schedule_id = 2;
   */
  scheduleId: string;

  /**
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message idp.health.v1.ManageScheduleResponse.
 * Use `create(ManageScheduleResponseSchema)` to create a new message.
 */
export const ManageScheduleResponseSchema: GenMessage<ManageScheduleResponse> = /*@__PURE__*/
  messageDesc(file_idp_health_v1_health, 2);

/**
 * @generated from message idp.health.v1.DeleteScheduleRequest
 */
export type DeleteScheduleRequest = Message<"idp.health.v1.DeleteScheduleRequest"> & {
  /**
   * @generated from field: string app_id = 1;
   */
  appId: string;
};

/**
 * Describes the message idp.health.v1.DeleteScheduleRequest.
 * Use `create(DeleteScheduleRequestSchema)` to create a new message.
 */
export const DeleteScheduleRequestSchema: GenMessage<DeleteScheduleRequest> = /*@__PURE__*/
  messageDesc(file_idp_health_v1_health, 3);

/**
 * @generated from message idp.health.v1.DeleteScheduleResponse
 */
export type DeleteScheduleResponse = Message<"idp.health.v1.DeleteScheduleResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message idp.health.v1.DeleteScheduleResponse.
 * Use `create(DeleteScheduleResponseSchema)` to create a new message.
 */
export const DeleteScheduleResponseSchema: GenMessage<DeleteScheduleResponse> = /*@__PURE__*/
  messageDesc(file_idp_health_v1_health, 4);

/**
 * @generated from service idp.health.v1.HealthService
 */
export const HealthService: GenService<{
  /**
   * ManageSchedule creates, updates, or deletes a health check schedule for an app
   *
   * @generated from rpc idp.health.v1.HealthService.ManageSchedule
   */
  manageSchedule: {
    methodKind: "unary";
    input: typeof ManageScheduleRequestSchema;
    output: typeof ManageScheduleResponseSchema;
  },
  /**
   * DeleteSchedule removes a health check schedule for an app
   *
   * @generated from rpc idp.health.v1.HealthService.DeleteSchedule
   */
  deleteSchedule: {
    methodKind: "unary";
    input: typeof DeleteScheduleRequestSchema;
    output: typeof DeleteScheduleResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_idp_health_v1_health, 0);

