// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file idp/health/v1/health.proto (package idp.health.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteScheduleRequest, DeleteScheduleResponse, ManageScheduleRequest, ManageScheduleResponse } from "./health_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service idp.health.v1.HealthService
 */
export const HealthService = {
  typeName: "idp.health.v1.HealthService",
  methods: {
    /**
     * ManageSchedule creates, updates, or deletes a health check schedule for an app
     *
     * @generated from rpc idp.health.v1.HealthService.ManageSchedule
     */
    manageSchedule: {
      name: "ManageSchedule",
      I: ManageScheduleRequest,
      O: ManageScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteSchedule removes a health check schedule for an app
     *
     * @generated from rpc idp.health.v1.HealthService.DeleteSchedule
     */
    deleteSchedule: {
      name: "DeleteSchedule",
      I: DeleteScheduleRequest,
      O: DeleteScheduleResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

