// proto/idp/gateway/v1/gateway.proto

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file idp/gateway/v1/gateway.proto (package idp.gateway.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteVirtualClusterRequest, DeleteVirtualClusterResponse, GetFullConfigRequest, GetFullConfigResponse, GetStatusRequest, GetStatusResponse, ListVirtualClustersRequest, ListVirtualClustersResponse, SetVirtualClusterReadOnlyRequest, SetVirtualClusterReadOnlyResponse, UpsertVirtualClusterRequest, UpsertVirtualClusterResponse } from "./gateway_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service idp.gateway.v1.BifrostAdminService
 */
export const BifrostAdminService = {
  typeName: "idp.gateway.v1.BifrostAdminService",
  methods: {
    /**
     * Virtual Cluster lifecycle
     *
     * @generated from rpc idp.gateway.v1.BifrostAdminService.UpsertVirtualCluster
     */
    upsertVirtualCluster: {
      name: "UpsertVirtualCluster",
      I: UpsertVirtualClusterRequest,
      O: UpsertVirtualClusterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.gateway.v1.BifrostAdminService.DeleteVirtualCluster
     */
    deleteVirtualCluster: {
      name: "DeleteVirtualCluster",
      I: DeleteVirtualClusterRequest,
      O: DeleteVirtualClusterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.gateway.v1.BifrostAdminService.SetVirtualClusterReadOnly
     */
    setVirtualClusterReadOnly: {
      name: "SetVirtualClusterReadOnly",
      I: SetVirtualClusterReadOnlyRequest,
      O: SetVirtualClusterReadOnlyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Full sync (startup reconciliation)
     *
     * @generated from rpc idp.gateway.v1.BifrostAdminService.GetFullConfig
     */
    getFullConfig: {
      name: "GetFullConfig",
      I: GetFullConfigRequest,
      O: GetFullConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Health & observability
     *
     * @generated from rpc idp.gateway.v1.BifrostAdminService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.gateway.v1.BifrostAdminService.ListVirtualClusters
     */
    listVirtualClusters: {
      name: "ListVirtualClusters",
      I: ListVirtualClustersRequest,
      O: ListVirtualClustersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

