import type { CollectionConfig } from 'payload'
import { workspaceScopedRead } from './access'

/**
 * EntityScores — one row per (entity, scorecard) PLUS one `overall` row per
 * entity (Entity Scores & Golden Paths,
 * docs/plans/2026-07-01-entity-scores-and-golden-paths.md).
 *
 * Like ScorecardRuleResults, this is machine-written — no direct user writes.
 * `recomputeWorkspaceScores` (lib/scorecards/scoring.ts orchestration, called
 * from runScorecardEvaluation and the internal recompute-scores backfill
 * endpoint) upserts:
 *   - a `scope: 'scorecard'` row per (entity, scorecard) it evaluates, and
 *   - a `scope: 'overall'` row for EVERY catalog entity in the workspace (the
 *     coverage invariant — entities no scorecard touches still get a row,
 *     seeded from their type's `baseValue`).
 *
 * `score` is the single field both scopes share (0-100). `scorecard` scope
 * additionally carries the achieved ladder rung (`levelName`/`levelRank`) and
 * the rule tally/weights backing `score`. `overall` scope additionally carries
 * `baseValue` (the inherited value this row was seeded from, kept for
 * transparency even once scorecards replace it) and `goldenPathAlignment` (%
 * of the entity type's golden-path expectations met).
 */
export const EntityScores: CollectionConfig = {
  slug: 'entity-scores',
  admin: {
    useAsTitle: 'id',
    group: 'Scorecards',
    defaultColumns: ['entity', 'scope', 'scorecard', 'score', 'evaluatedAt'],
    description: 'Per-entity scores (per-scorecard + overall) — generated by evaluation.',
  },
  access: {
    read: workspaceScopedRead,
    // Mutations happen through the scoring orchestrator with overrideAccess;
    // no direct user writes.
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  fields: [
    {
      name: 'workspace',
      type: 'relationship',
      relationTo: 'workspaces',
      required: true,
      index: true,
    },
    {
      name: 'entity',
      type: 'relationship',
      relationTo: 'catalog-entities',
      required: true,
      index: true,
    },
    {
      name: 'scope',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Scorecard', value: 'scorecard' },
        { label: 'Overall', value: 'overall' },
      ],
    },
    {
      name: 'scorecard',
      type: 'relationship',
      relationTo: 'scorecards',
      index: true,
      admin: { description: 'Required when scope=scorecard; absent for scope=overall.' },
    },
    { name: 'score', type: 'number', required: true, index: true, min: 0, max: 100 },
    {
      name: 'levelName',
      type: 'text',
      admin: { description: 'Achieved ladder rung (scorecard scope).' },
    },
    { name: 'levelRank', type: 'number' },
    { name: 'passedRules', type: 'number' },
    { name: 'totalRules', type: 'number' },
    {
      name: 'weightedPoints',
      type: 'number',
      admin: { description: 'Weighted sum of passed rules backing `score`.' },
    },
    { name: 'maxPoints', type: 'number' },
    {
      name: 'baseValue',
      type: 'number',
      admin: { description: 'The inherited value that seeded this score (overall scope).' },
    },
    {
      name: 'goldenPathAlignment',
      type: 'number',
      min: 0,
      max: 100,
      admin: { description: '% of golden-path expectations met (overall scope).' },
    },
    { name: 'evaluatedAt', type: 'date' },
  ],
  indexes: [
    { fields: ['workspace', 'entity', 'scope'] },
    { fields: ['workspace', 'scope', 'score'] },
    { fields: ['scorecard', 'score'] },
  ],
  timestamps: true,
}
