import type { CollectionConfig } from 'payload'
import { platformAdminFieldUpdate, workspaceScopedRead, workspaceScopedMutate } from './access'
import { validateActionItemRelationships } from './invariants'

/**
 * InitiativeActionItems — per-entity remediation tasks within an initiative
 * (IDP refocus P2). Typically one per (entity, failing rule); tracks who owns
 * the fix and its status.
 */
export const InitiativeActionItems: CollectionConfig = {
  slug: 'initiative-action-items',
  admin: {
    useAsTitle: 'id',
    group: 'Scorecards',
    defaultColumns: ['initiative', 'entity', 'status', 'assignee', 'updatedAt'],
    description: 'Remediation tasks tracked under an initiative.',
  },
  access: {
    read: workspaceScopedRead,
    // Generated by initiative sync through trusted overrideAccess writes.
    create: () => false,
    update: workspaceScopedMutate('initiative-action-items', ['owner', 'admin', 'member']),
    delete: workspaceScopedMutate('initiative-action-items', ['owner', 'admin']),
  },
  hooks: { beforeValidate: [validateActionItemRelationships] },
  fields: [
    {
      name: 'workspace',
      type: 'relationship',
      relationTo: 'workspaces',
      required: true,
      index: true,
      access: { update: platformAdminFieldUpdate },
    },
    {
      name: 'initiative',
      type: 'relationship',
      relationTo: 'initiatives',
      required: true,
      index: true,
      access: { update: platformAdminFieldUpdate },
    },
    {
      name: 'entity',
      type: 'relationship',
      relationTo: 'catalog-entities',
      required: true,
      index: true,
      access: { update: platformAdminFieldUpdate },
    },
    {
      name: 'rule',
      type: 'relationship',
      relationTo: 'scorecard-rules',
      access: { update: platformAdminFieldUpdate },
    },
    { name: 'assignee', type: 'relationship', relationTo: 'users' },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'open',
      options: [
        { label: 'Open', value: 'open' },
        { label: 'In progress', value: 'in-progress' },
        { label: 'Done', value: 'done' },
        { label: 'Waived', value: 'waived' },
      ],
    },
    { name: 'notes', type: 'textarea' },
  ],
  // entity is already indexed via `index: true`; keep the compound for list views.
  indexes: [
    { fields: ['initiative', 'entity', 'rule'], unique: true },
    { fields: ['workspace', 'initiative'] },
  ],
  timestamps: true,
}
