import type { CollectionConfig } from 'payload'
import { workspaceScopedRead } from './access'

/**
 * ScoreSnapshots — append-only score history (Scorecard Reports & Insights,
 * docs/plans/2026-07-01-scorecard-reports.md, WP1).
 *
 * Unlike `entity-scores` (upserted in place — only the latest state), this
 * collection is APPENDED to on every capture, giving the reports UI a trend
 * line to chart. Machine-written like `scorecard-rule-results` /
 * `entity-scores` — no direct user writes.
 *
 * `captureScoreSnapshots` (lib/scorecards/snapshots.ts) writes one row per
 * scope per capture:
 *   - `scope: 'workspace'` — org-wide rollup of every entity's overall score.
 *   - `scope: 'scorecard'` — one row per enabled scorecard (avg score across
 *     entities it scores, plus pass rate + level distribution).
 *   - `scope: 'team'` — one row per owning team (catalog-entities kind='team'),
 *     rolling up the overall scores of entities that team owns.
 *
 * Called fire-and-forget at the end of `runScorecardEvaluation` and
 * `recomputeWorkspaceScores`, throttled to once per 30 minutes (keyed on the
 * newest `workspace`-scope snapshot) unless `force` is passed, and exposed via
 * `/api/internal/scorecards/capture-snapshots` for manual/backfill capture.
 */
export const ScoreSnapshots: CollectionConfig = {
  slug: 'score-snapshots',
  admin: {
    useAsTitle: 'id',
    group: 'Scorecards',
    defaultColumns: ['workspace', 'scope', 'scorecard', 'team', 'avgScore', 'capturedAt'],
    description: 'Append-only score history — generated by evaluation for the reports trend line.',
  },
  access: {
    read: workspaceScopedRead,
    // Mutations happen through captureScoreSnapshots with overrideAccess; no
    // direct user writes.
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  fields: [
    {
      name: 'workspace',
      type: 'relationship',
      relationTo: 'workspaces',
      required: true,
      index: true,
    },
    {
      name: 'scope',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Workspace', value: 'workspace' },
        { label: 'Scorecard', value: 'scorecard' },
        { label: 'Team', value: 'team' },
      ],
    },
    {
      name: 'scorecard',
      type: 'relationship',
      relationTo: 'scorecards',
      index: true,
      admin: { description: 'Set when scope=scorecard.' },
    },
    {
      name: 'team',
      type: 'relationship',
      relationTo: 'catalog-entities',
      index: true,
      admin: { description: "Set when scope=team (a catalog-entities row of kind 'team')." },
    },
    {
      name: 'avgScore',
      type: 'number',
      required: true,
      admin: {
        description:
          'Mean overall score (workspace/team scope) or mean scorecard score (scorecard scope).',
      },
    },
    {
      name: 'avgAlignment',
      type: 'number',
      admin: { description: 'Mean golden-path alignment (workspace/team scope).' },
    },
    { name: 'entityCount', type: 'number', required: true, admin: { description: 'Entities behind the average.' } },
    {
      name: 'passRate',
      type: 'number',
      admin: { description: 'Scorecard scope: passing rule results / total rule results.' },
    },
    {
      name: 'levelDistribution',
      type: 'json',
      admin: { description: "Scorecard scope: { [levelName]: count, unranked: count }." },
    },
    {
      name: 'captureKey',
      type: 'text',
      index: true,
      admin: { description: 'Stable Temporal/manual capture identifier for retry recovery.' },
    },
    {
      name: 'snapshotKey',
      type: 'text',
      unique: true,
      admin: { description: 'Per-row idempotency key within a keyed capture set.' },
    },
    { name: 'capturedAt', type: 'date', required: true, index: true },
  ],
  indexes: [
    { fields: ['workspace', 'scope', 'capturedAt'] },
    { fields: ['scorecard', 'capturedAt'] },
  ],
  timestamps: true,
}
