import type { CollectionConfig } from 'payload'
import { workspaceScopedRead } from './access'

/**
 * ScorecardRuleResults — one row per (rule, entity) evaluation (IDP refocus P2).
 *
 * Auto-generated by the evaluator (lib/scorecards/evaluate → runScorecardEvaluation),
 * idempotent per (scorecard, rule, entity). This is the QUERYABLE source of
 * truth (Port 2.0): the UI rollup, entity score chips, and P4 automations all
 * read it. Writes come from the eval runner (server action or internal API)
 * with overrideAccess; users only read.
 */
export const ScorecardRuleResults: CollectionConfig = {
  slug: 'scorecard-rule-results',
  admin: {
    useAsTitle: 'id',
    group: 'Scorecards',
    defaultColumns: ['entity', 'rule', 'passed', 'evaluatedAt'],
    description: 'Per-entity pass/fail results — generated by evaluation.',
  },
  access: {
    read: workspaceScopedRead,
    // Mutations happen through the eval runner with overrideAccess; no direct
    // user writes.
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  hooks: {
    // Automation event source (IDP refocus P4): a pass→fail transition is the
    // drift signal. Fire-and-forget — a dispatch failure must never block the
    // evaluation write.
    afterChange: [
      ({ doc, previousDoc, operation, req }) => {
        ;(async () => {
          try {
            const { emitRuleResultChanged } = await import('@/lib/automations/emit')
            await emitRuleResultChanged(req.payload, { doc, previousDoc, operation })
          } catch (err) {
            console.error('[ScorecardRuleResults Hook] automation emit failed:', err)
          }
        })()
        return doc
      },
    ],
  },
  fields: [
    {
      name: 'workspace',
      type: 'relationship',
      relationTo: 'workspaces',
      required: true,
      index: true,
    },
    {
      name: 'scorecard',
      type: 'relationship',
      relationTo: 'scorecards',
      required: true,
      index: true,
    },
    {
      name: 'rule',
      type: 'relationship',
      relationTo: 'scorecard-rules',
      required: true,
      index: true,
    },
    {
      name: 'entity',
      type: 'relationship',
      relationTo: 'catalog-entities',
      required: true,
      index: true,
    },
    { name: 'passed', type: 'checkbox', required: true, index: true },
    { name: 'evaluatedAt', type: 'date' },
    {
      name: 'detail',
      type: 'textarea',
      admin: { description: 'Human-readable why-pass/why-fail.' },
    },
  ],
  indexes: [
    { fields: ['scorecard', 'rule', 'entity'], unique: true },
    { fields: ['workspace', 'entity', 'passed'] },
    { fields: ['scorecard', 'rule'] },
    { fields: ['scorecard', 'entity'] },
  ],
  timestamps: true,
}
