// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file idp/launch/v1/launch.proto (package idp.launch.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AbortLaunchRequest, AbortLaunchResponse, ApproveLaunchRequest, ApproveLaunchResponse, DeorbitLaunchRequest, DeorbitLaunchResponse, DeployToLaunchRequest, DeployToLaunchResponse, GetLaunchProgressRequest, GetLaunchProgressResponse, StartLaunchRequest, StartLaunchResponse } from "./launch_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service idp.launch.v1.LaunchService
 */
export const LaunchService = {
  typeName: "idp.launch.v1.LaunchService",
  methods: {
    /**
     * @generated from rpc idp.launch.v1.LaunchService.StartLaunch
     */
    startLaunch: {
      name: "StartLaunch",
      I: StartLaunchRequest,
      O: StartLaunchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.launch.v1.LaunchService.GetLaunchProgress
     */
    getLaunchProgress: {
      name: "GetLaunchProgress",
      I: GetLaunchProgressRequest,
      O: GetLaunchProgressResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.launch.v1.LaunchService.ApproveLaunch
     */
    approveLaunch: {
      name: "ApproveLaunch",
      I: ApproveLaunchRequest,
      O: ApproveLaunchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.launch.v1.LaunchService.DeorbitLaunch
     */
    deorbitLaunch: {
      name: "DeorbitLaunch",
      I: DeorbitLaunchRequest,
      O: DeorbitLaunchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.launch.v1.LaunchService.AbortLaunch
     */
    abortLaunch: {
      name: "AbortLaunch",
      I: AbortLaunchRequest,
      O: AbortLaunchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.launch.v1.LaunchService.DeployToLaunch
     */
    deployToLaunch: {
      name: "DeployToLaunch",
      I: DeployToLaunchRequest,
      O: DeployToLaunchResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

