// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file auth.proto (package idp.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { EntityMetadata } from "./common_pb";
import { file_common } from "./common_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvEgtpZHAuYXV0aC52MSLmAgoEVXNlchIvCghtZXRhZGF0YRgBIAEoCzIdLmlkcC5jb21tb24udjEuRW50aXR5TWV0YWRhdGESDQoFZW1haWwYAiABKAkSEAoIdXNlcm5hbWUYAyABKAkSFAoMZGlzcGxheV9uYW1lGAQgASgJEhIKCmF2YXRhcl91cmwYBSABKAkSMAoNYXV0aF9wcm92aWRlchgGIAEoDjIZLmlkcC5hdXRoLnYxLkF1dGhQcm92aWRlchITCgtleHRlcm5hbF9pZBgHIAEoCRINCgV0aXRsZRgIIAEoCRILCgNiaW8YCSABKAkSEAoIbG9jYXRpb24YCiABKAkSEAoIdGltZXpvbmUYCyABKAkSJwoGc3RhdHVzGAwgASgOMhcuaWRwLmF1dGgudjEuVXNlclN0YXR1cxIyCg5sYXN0X2FjdGl2ZV9hdBgNIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAi6gEKC1Rva2VuQ2xhaW1zEg8KB3VzZXJfaWQYASABKAkSDQoFZW1haWwYAiABKAkSEAoIdXNlcm5hbWUYAyABKAkSFQoNd29ya3NwYWNlX2lkcxgEIAMoCRIzCg93b3Jrc3BhY2Vfcm9sZXMYBSADKAsyGi5pZHAuYXV0aC52MS5Xb3Jrc3BhY2VSb2xlEi0KCWlzc3VlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZXhwaXJlc19hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiMwoNV29ya3NwYWNlUm9sZRIUCgx3b3Jrc3BhY2VfaWQYASABKAkSDAoEcm9sZRgCIAEoCSLlAQoHU2Vzc2lvbhIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhMKC2RldmljZV9pbmZvGAMgASgJEhIKCmlwX2FkZHJlc3MYBCABKAkSLgoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZXhwaXJlc19hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASNAoQbGFzdF9hY2Nlc3NlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAqlgEKDEF1dGhQcm92aWRlchIdChlBVVRIX1BST1ZJREVSX1VOU1BFQ0lGSUVEEAASFwoTQVVUSF9QUk9WSURFUl9MT0NBTBABEhgKFEFVVEhfUFJPVklERVJfR0lUSFVCEAISGAoUQVVUSF9QUk9WSURFUl9HT09HTEUQAxIaChZBVVRIX1BST1ZJREVSX0FaVVJFX0FEEAQqdgoKVXNlclN0YXR1cxIbChdVU0VSX1NUQVRVU19VTlNQRUNJRklFRBAAEhYKElVTRVJfU1RBVFVTX0FDVElWRRABEhgKFFVTRVJfU1RBVFVTX0lOQUNUSVZFEAISGQoVVVNFUl9TVEFUVVNfU1VTUEVOREVEEANCPlo8Z2l0aHViLmNvbS9kcmV3cGF5bWVudC9vcmJpdC9wcm90by9nZW4vZ28vaWRwL2F1dGgvdjE7YXV0aHYxYgZwcm90bzM", [file_common, file_google_protobuf_timestamp]);

/**
 * User entity
 *
 * @generated from message idp.auth.v1.User
 */
export type User = Message<"idp.auth.v1.User"> & {
  /**
   * @generated from field: idp.common.v1.EntityMetadata metadata = 1;
   */
  metadata?: EntityMetadata;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string display_name = 4;
   */
  displayName: string;

  /**
   * @generated from field: string avatar_url = 5;
   */
  avatarUrl: string;

  /**
   * Authentication
   *
   * @generated from field: idp.auth.v1.AuthProvider auth_provider = 6;
   */
  authProvider: AuthProvider;

  /**
   * @generated from field: string external_id = 7;
   */
  externalId: string;

  /**
   * Profile
   *
   * @generated from field: string title = 8;
   */
  title: string;

  /**
   * @generated from field: string bio = 9;
   */
  bio: string;

  /**
   * @generated from field: string location = 10;
   */
  location: string;

  /**
   * @generated from field: string timezone = 11;
   */
  timezone: string;

  /**
   * Status
   *
   * @generated from field: idp.auth.v1.UserStatus status = 12;
   */
  status: UserStatus;

  /**
   * @generated from field: google.protobuf.Timestamp last_active_at = 13;
   */
  lastActiveAt?: Timestamp;
};

/**
 * Describes the message idp.auth.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_auth, 0);

/**
 * JWT token claims
 *
 * @generated from message idp.auth.v1.TokenClaims
 */
export type TokenClaims = Message<"idp.auth.v1.TokenClaims"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: repeated string workspace_ids = 4;
   */
  workspaceIds: string[];

  /**
   * @generated from field: repeated idp.auth.v1.WorkspaceRole workspace_roles = 5;
   */
  workspaceRoles: WorkspaceRole[];

  /**
   * @generated from field: google.protobuf.Timestamp issued_at = 6;
   */
  issuedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 7;
   */
  expiresAt?: Timestamp;
};

/**
 * Describes the message idp.auth.v1.TokenClaims.
 * Use `create(TokenClaimsSchema)` to create a new message.
 */
export const TokenClaimsSchema: GenMessage<TokenClaims> = /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * @generated from message idp.auth.v1.WorkspaceRole
 */
export type WorkspaceRole = Message<"idp.auth.v1.WorkspaceRole"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * "owner", "admin", "member", "viewer"
   *
   * @generated from field: string role = 2;
   */
  role: string;
};

/**
 * Describes the message idp.auth.v1.WorkspaceRole.
 * Use `create(WorkspaceRoleSchema)` to create a new message.
 */
export const WorkspaceRoleSchema: GenMessage<WorkspaceRole> = /*@__PURE__*/
  messageDesc(file_auth, 2);

/**
 * Session information
 *
 * @generated from message idp.auth.v1.Session
 */
export type Session = Message<"idp.auth.v1.Session"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string device_info = 3;
   */
  deviceInfo: string;

  /**
   * @generated from field: string ip_address = 4;
   */
  ipAddress: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 6;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_accessed_at = 7;
   */
  lastAccessedAt?: Timestamp;
};

/**
 * Describes the message idp.auth.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema: GenMessage<Session> = /*@__PURE__*/
  messageDesc(file_auth, 3);

/**
 * @generated from enum idp.auth.v1.AuthProvider
 */
export enum AuthProvider {
  /**
   * @generated from enum value: AUTH_PROVIDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: AUTH_PROVIDER_LOCAL = 1;
   */
  LOCAL = 1,

  /**
   * @generated from enum value: AUTH_PROVIDER_GITHUB = 2;
   */
  GITHUB = 2,

  /**
   * @generated from enum value: AUTH_PROVIDER_GOOGLE = 3;
   */
  GOOGLE = 3,

  /**
   * @generated from enum value: AUTH_PROVIDER_AZURE_AD = 4;
   */
  AZURE_AD = 4,
}

/**
 * Describes the enum idp.auth.v1.AuthProvider.
 */
export const AuthProviderSchema: GenEnum<AuthProvider> = /*@__PURE__*/
  enumDesc(file_auth, 0);

/**
 * @generated from enum idp.auth.v1.UserStatus
 */
export enum UserStatus {
  /**
   * @generated from enum value: USER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: USER_STATUS_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: USER_STATUS_SUSPENDED = 3;
   */
  SUSPENDED = 3,
}

/**
 * Describes the enum idp.auth.v1.UserStatus.
 */
export const UserStatusSchema: GenEnum<UserStatus> = /*@__PURE__*/
  enumDesc(file_auth, 1);

