// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file knowledge.proto (package idp.knowledge.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddCommentRequest, AddCommentResponse, CreateKnowledgeSpaceRequest, CreateKnowledgeSpaceResponse, CreatePageRequest, CreatePageResponse, DeleteCommentRequest, DeleteCommentResponse, DeleteKnowledgeSpaceRequest, DeleteKnowledgeSpaceResponse, DeletePageRequest, DeletePageResponse, GetKnowledgeSpaceRequest, GetKnowledgeSpaceResponse, GetPageRequest, GetPageResponse, ListCommentsRequest, ListCommentsResponse, ListKnowledgeSpacesRequest, ListKnowledgeSpacesResponse, ListPagesRequest, ListPagesResponse, SearchContentRequest, SearchContentResponse, UpdateCommentRequest, UpdateCommentResponse, UpdateKnowledgeSpaceRequest, UpdateKnowledgeSpaceResponse, UpdatePageRequest, UpdatePageResponse } from "./knowledge_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Knowledge Management Service
 *
 * @generated from service idp.knowledge.v1.KnowledgeService
 */
export const KnowledgeService = {
  typeName: "idp.knowledge.v1.KnowledgeService",
  methods: {
    /**
     * Knowledge Space management
     *
     * @generated from rpc idp.knowledge.v1.KnowledgeService.CreateKnowledgeSpace
     */
    createKnowledgeSpace: {
      name: "CreateKnowledgeSpace",
      I: CreateKnowledgeSpaceRequest,
      O: CreateKnowledgeSpaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.GetKnowledgeSpace
     */
    getKnowledgeSpace: {
      name: "GetKnowledgeSpace",
      I: GetKnowledgeSpaceRequest,
      O: GetKnowledgeSpaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.ListKnowledgeSpaces
     */
    listKnowledgeSpaces: {
      name: "ListKnowledgeSpaces",
      I: ListKnowledgeSpacesRequest,
      O: ListKnowledgeSpacesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.UpdateKnowledgeSpace
     */
    updateKnowledgeSpace: {
      name: "UpdateKnowledgeSpace",
      I: UpdateKnowledgeSpaceRequest,
      O: UpdateKnowledgeSpaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.DeleteKnowledgeSpace
     */
    deleteKnowledgeSpace: {
      name: "DeleteKnowledgeSpace",
      I: DeleteKnowledgeSpaceRequest,
      O: DeleteKnowledgeSpaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Page management
     *
     * @generated from rpc idp.knowledge.v1.KnowledgeService.CreatePage
     */
    createPage: {
      name: "CreatePage",
      I: CreatePageRequest,
      O: CreatePageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.GetPage
     */
    getPage: {
      name: "GetPage",
      I: GetPageRequest,
      O: GetPageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.ListPages
     */
    listPages: {
      name: "ListPages",
      I: ListPagesRequest,
      O: ListPagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.UpdatePage
     */
    updatePage: {
      name: "UpdatePage",
      I: UpdatePageRequest,
      O: UpdatePageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.DeletePage
     */
    deletePage: {
      name: "DeletePage",
      I: DeletePageRequest,
      O: DeletePageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Content search
     *
     * @generated from rpc idp.knowledge.v1.KnowledgeService.SearchContent
     */
    searchContent: {
      name: "SearchContent",
      I: SearchContentRequest,
      O: SearchContentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Comments
     *
     * @generated from rpc idp.knowledge.v1.KnowledgeService.AddComment
     */
    addComment: {
      name: "AddComment",
      I: AddCommentRequest,
      O: AddCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.ListComments
     */
    listComments: {
      name: "ListComments",
      I: ListCommentsRequest,
      O: ListCommentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.UpdateComment
     */
    updateComment: {
      name: "UpdateComment",
      I: UpdateCommentRequest,
      O: UpdateCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.knowledge.v1.KnowledgeService.DeleteComment
     */
    deleteComment: {
      name: "DeleteComment",
      I: DeleteCommentRequest,
      O: DeleteCommentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

