// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file plugins.proto (package idp.plugins.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DisablePluginRequest, DisablePluginResponse, EnablePluginRequest, EnablePluginResponse, GetPluginRequest, GetPluginResponse, GetPluginSchemaRequest, GetPluginSchemaResponse, ListPluginsRequest, ListPluginsResponse, ProxyPluginRequestMessage, ProxyPluginResponse, UpdatePluginConfigRequest, UpdatePluginConfigResponse } from "./plugins_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * PluginsService provides access to Backstage community plugins
 * This service acts as a proxy between Orbit's frontend and Backstage backend,
 * enforcing workspace isolation and handling authentication.
 *
 * @generated from service idp.plugins.v1.PluginsService
 */
export const PluginsService = {
  typeName: "idp.plugins.v1.PluginsService",
  methods: {
    /**
     * ListPlugins returns all available plugins for a workspace
     * Returns both enabled and disabled plugins with their configuration status
     *
     * @generated from rpc idp.plugins.v1.PluginsService.ListPlugins
     */
    listPlugins: {
      name: "ListPlugins",
      I: ListPluginsRequest,
      O: ListPluginsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetPlugin returns details for a specific plugin
     *
     * @generated from rpc idp.plugins.v1.PluginsService.GetPlugin
     */
    getPlugin: {
      name: "GetPlugin",
      I: GetPluginRequest,
      O: GetPluginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ProxyPluginRequest is a generic proxy that forwards requests to Backstage
     * This allows adding new plugins without changing the proto definition
     * All plugin-specific endpoints are accessed through this single method
     *
     * @generated from rpc idp.plugins.v1.PluginsService.ProxyPluginRequest
     */
    proxyPluginRequest: {
      name: "ProxyPluginRequest",
      I: ProxyPluginRequestMessage,
      O: ProxyPluginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetPluginSchema returns the schema for a specific plugin's data
     * Used by frontend to dynamically render plugin data
     *
     * @generated from rpc idp.plugins.v1.PluginsService.GetPluginSchema
     */
    getPluginSchema: {
      name: "GetPluginSchema",
      I: GetPluginSchemaRequest,
      O: GetPluginSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * EnablePlugin enables a plugin for a workspace
     *
     * @generated from rpc idp.plugins.v1.PluginsService.EnablePlugin
     */
    enablePlugin: {
      name: "EnablePlugin",
      I: EnablePluginRequest,
      O: EnablePluginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DisablePlugin disables a plugin for a workspace
     *
     * @generated from rpc idp.plugins.v1.PluginsService.DisablePlugin
     */
    disablePlugin: {
      name: "DisablePlugin",
      I: DisablePluginRequest,
      O: DisablePluginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdatePluginConfig updates the configuration for a plugin
     *
     * @generated from rpc idp.plugins.v1.PluginsService.UpdatePluginConfig
     */
    updatePluginConfig: {
      name: "UpdatePluginConfig",
      I: UpdatePluginConfigRequest,
      O: UpdatePluginConfigResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

