// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file workspace.proto (package idp.workspace.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddMemberRequest, AddMemberResponse, CreateWorkspaceRequest, CreateWorkspaceResponse, DeleteWorkspaceRequest, DeleteWorkspaceResponse, GetSettingsRequest, GetSettingsResponse, GetWorkspaceRequest, GetWorkspaceResponse, ListMembersRequest, ListMembersResponse, ListWorkspacesRequest, ListWorkspacesResponse, RemoveMemberRequest, RemoveMemberResponse, UpdateMemberRoleRequest, UpdateMemberRoleResponse, UpdateSettingsRequest, UpdateSettingsResponse, UpdateWorkspaceRequest, UpdateWorkspaceResponse } from "./workspace_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Workspace Management Service
 *
 * @generated from service idp.workspace.v1.WorkspaceService
 */
export const WorkspaceService = {
  typeName: "idp.workspace.v1.WorkspaceService",
  methods: {
    /**
     * Create a new workspace
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.CreateWorkspace
     */
    createWorkspace: {
      name: "CreateWorkspace",
      I: CreateWorkspaceRequest,
      O: CreateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get workspace by ID
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.GetWorkspace
     */
    getWorkspace: {
      name: "GetWorkspace",
      I: GetWorkspaceRequest,
      O: GetWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List workspaces for current user
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.ListWorkspaces
     */
    listWorkspaces: {
      name: "ListWorkspaces",
      I: ListWorkspacesRequest,
      O: ListWorkspacesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update workspace
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.UpdateWorkspace
     */
    updateWorkspace: {
      name: "UpdateWorkspace",
      I: UpdateWorkspaceRequest,
      O: UpdateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete workspace
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.DeleteWorkspace
     */
    deleteWorkspace: {
      name: "DeleteWorkspace",
      I: DeleteWorkspaceRequest,
      O: DeleteWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Workspace Members
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.AddMember
     */
    addMember: {
      name: "AddMember",
      I: AddMemberRequest,
      O: AddMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.workspace.v1.WorkspaceService.UpdateMemberRole
     */
    updateMemberRole: {
      name: "UpdateMemberRole",
      I: UpdateMemberRoleRequest,
      O: UpdateMemberRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.workspace.v1.WorkspaceService.RemoveMember
     */
    removeMember: {
      name: "RemoveMember",
      I: RemoveMemberRequest,
      O: RemoveMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.workspace.v1.WorkspaceService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListMembersRequest,
      O: ListMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Workspace Settings
     *
     * @generated from rpc idp.workspace.v1.WorkspaceService.UpdateSettings
     */
    updateSettings: {
      name: "UpdateSettings",
      I: UpdateSettingsRequest,
      O: UpdateSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc idp.workspace.v1.WorkspaceService.GetSettings
     */
    getSettings: {
      name: "GetSettings",
      I: GetSettingsRequest,
      O: GetSettingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

