// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file idp/deployment/v1/deployment.proto (package idp.deployment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetDeploymentProgressRequest, GetDeploymentProgressResponse, StartDeploymentWorkflowRequest, StartDeploymentWorkflowResponse } from "./deployment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * DeploymentService handles deployment workflow operations
 *
 * @generated from service idp.deployment.v1.DeploymentService
 */
export const DeploymentService = {
  typeName: "idp.deployment.v1.DeploymentService",
  methods: {
    /**
     * Start a new deployment workflow
     *
     * @generated from rpc idp.deployment.v1.DeploymentService.StartDeploymentWorkflow
     */
    startDeploymentWorkflow: {
      name: "StartDeploymentWorkflow",
      I: StartDeploymentWorkflowRequest,
      O: StartDeploymentWorkflowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get current progress of a deployment
     *
     * @generated from rpc idp.deployment.v1.DeploymentService.GetDeploymentProgress
     */
    getDeploymentProgress: {
      name: "GetDeploymentProgress",
      I: GetDeploymentProgressRequest,
      O: GetDeploymentProgressResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

