'use server'

/**
 * Consumer-run-only server actions for `/self-service/templates/[id]/run/**`
 * (Phase 2 plan Tasks 16-17). Deliberately kept in its OWN file rather than
 * folded into `authoring-actions.ts`: that file is also being edited by the
 * authoring-shell worktree and the scaffolder-dispatch branch, so a new
 * small helper here avoids stacking merge conflicts onto a large shared
 * file. `startDryRun`/`planRun`/`startRun`/`getRun` (the run lifecycle
 * itself) still live in `authoring-actions.ts` — this file only adds the
 * slug→definition lookup the consumer routes need that no existing action
 * provides (everything else there addresses a definition by Payload id).
 *
 * Mirrors `authoring-actions.ts#getTemplateDefinition`'s gating exactly:
 * `draft`/`deprecated` rows require `canManageTemplateDefinitions` on the
 * row's workspace, `published` rows require `canRunTemplateDefinition`.
 * Returns `null` on denial or not-found so callers 404 rather than leak
 * existence.
 */

import { getPayload } from 'payload'
import config from '@payload-config'
import { getCurrentUser, getPayloadUserFromSession } from '@/lib/auth/session'
import { isPlatformAdmin } from '@/lib/access/workspace-access'
import {
  canManageTemplateDefinitions,
  canRunTemplateDefinition,
  canApproveScaffolderStep,
} from '@/lib/templates/authz'
import { resolveScaffolderApproval as resolveScaffolderApprovalRPC } from '@/lib/clients/template-client'
import type { TemplateDefinition as TemplateDefinitionDoc, ActionRun } from '@/payload-types'

function relId(value: unknown): string | null {
  if (!value) return null
  if (typeof value === 'string') return value
  if (typeof value === 'object' && 'id' in (value as Record<string, unknown>)) {
    return String((value as { id: unknown }).id)
  }
  return null
}

async function requireUserId(): Promise<string> {
  const uid = (await getCurrentUser())?.id
  if (!uid) throw new Error('Not authenticated')
  return uid
}

async function currentUserIsPlatformAdmin(): Promise<boolean> {
  const user = await getPayloadUserFromSession()
  return isPlatformAdmin(user)
}

/**
 * Loads a single template-definition by its Payload `id` OR its (globally
 * unique) `slug`, with `currentVersion` populated — the route param for
 * `/self-service/templates/[id]/**` is named `id` (Next.js requires one
 * consistent dynamic-segment name per path; the authoring-shell branch's
 * `[id]/edit` route already claims that name), but consumers still land
 * here with either a definition id OR its slug in that position, so both
 * must resolve. Tries `findByID` first (the common case: links generated by
 * this app always use the id); on a not-found, falls back to the slug
 * lookup. See module docblock for the gating rules, applied identically
 * regardless of which lookup resolved the row.
 */
export async function getTemplateDefinitionByIdOrSlug(
  idOrSlug: string,
): Promise<TemplateDefinitionDoc | null> {
  const payload = await getPayload({ config })
  const uid = await requireUserId()
  const isAdmin = await currentUserIsPlatformAdmin()

  let definition: TemplateDefinitionDoc | undefined
  try {
    definition = await payload.findByID({
      collection: 'template-definitions',
      id: idOrSlug,
      depth: 1,
      overrideAccess: true,
    })
  } catch {
    const found = await payload.find({
      collection: 'template-definitions',
      where: { slug: { equals: idOrSlug } },
      depth: 1,
      limit: 1,
      overrideAccess: true,
    })
    definition = found.docs[0]
  }
  if (!definition) return null

  const workspaceId = relId(definition.workspace)
  const allowed =
    definition.status === 'published'
      ? await canRunTemplateDefinition(payload, uid, workspaceId, isAdmin)
      : await canManageTemplateDefinitions(payload, uid, workspaceId, isAdmin)
  if (!allowed) return null

  return definition
}

/** Back-compat alias — kept for any caller still importing the pre-rename name. Prefer {@link getTemplateDefinitionByIdOrSlug}. */
export const getTemplateDefinitionBySlug = getTemplateDefinitionByIdOrSlug

// ---------------------------------------------------------------------------
// resolveScaffolderApproval — approve/reject an approval:request step
// (Phase 4 Task C)
// ---------------------------------------------------------------------------

/**
 * Resolves an `approval:request` step's mid-run gate on a running scaffolder
 * workflow.
 *
 * Authorization (plan §13 decision 6): the caller must be a workspace
 * owner/admin OR listed in the step's `approvers` — checked here, BEFORE the
 * RPC is called. The RPC's own tenant-isolation check
 * (`authorizeScaffolderRun`) is a second, independent layer, not a
 * substitute: the internal API key that reaches the repository service is
 * never itself an approver.
 *
 * The `approvers` list lives on the `pending-approvals` row the workflow
 * opened (`payload.approvers`), not on `action-runs` — that row is also
 * what proves `approvalId` actually belongs to this run, so a caller cannot
 * resolve an unrelated workflow's gate by guessing an id.
 */
export async function resolveScaffolderApproval(
  runId: string,
  approvalId: string,
  approved: boolean,
  comment?: string,
): Promise<{ ok: boolean; runId: string; errors?: string[] }> {
  const payload = await getPayload({ config })
  const user = await getCurrentUser()
  const uid = user?.id
  if (!uid) throw new Error('Not authenticated')
  const isAdmin = await currentUserIsPlatformAdmin()

  let run: ActionRun
  try {
    run = await payload.findByID({ collection: 'action-runs', id: runId, depth: 0, overrideAccess: true })
  } catch {
    throw new Error('Run not found')
  }
  const workspaceId = relId(run.workspace)
  if (!workspaceId) throw new Error('Run not found')
  if (!run.workflowId) throw new Error('This run has not been dispatched yet.')

  // Looked up by (runId, approvalId), NOT (workflowId, approvalId): a gate
  // opened inside a `fetch:template`-nested child workflow stamps the ROOT
  // run's id here (ScaffolderOpenApproval / scaffolder_approval.go's
  // runApprovalStep — the row's `runId` is always the outermost run's
  // action-runs doc id) but its OWN real Temporal workflow id in
  // `workflowId`, which for a nested gate is the CHILD's id, not this root
  // run's `run.workflowId`. Filtering on the root run id (this function's
  // `runId` param, exactly what the row carries either way) is what still
  // finds a nested gate; the row's own `workflowId` — read below, never
  // `run.workflowId` — is what the RPC actually needs to signal the right
  // execution.
  const gates = await payload.find({
    collection: 'pending-approvals',
    where: {
      and: [{ runId: { equals: runId } }, { approvalId: { equals: approvalId } }],
    },
    limit: 1,
    depth: 0,
    overrideAccess: true,
  })
  const gate = gates.docs[0]
  if (!gate) throw new Error('Approval gate not found')
  if (!gate.workflowId) throw new Error('Approval gate not found')

  const gatePayload =
    gate.payload && typeof gate.payload === 'object' && !Array.isArray(gate.payload)
      ? (gate.payload as { approvers?: unknown })
      : {}
  const approvers = Array.isArray(gatePayload.approvers)
    ? gatePayload.approvers.filter((a): a is string => typeof a === 'string')
    : []

  const canApprove = await canApproveScaffolderStep(payload, uid, user?.email, workspaceId, approvers, isAdmin)
  if (!canApprove) {
    throw new Error('You do not have permission to resolve this approval gate.')
  }

  // The RPC call itself is the one failure mode a caller who passed every
  // check above can still legitimately hit (the workflow already finished,
  // the worker is unavailable, a transient gRPC error, …), so it's caught
  // here and reported as a normal `{ ok: false }` result rather than an
  // uncaught throw — a `ConnectError` crossing the server-action boundary
  // otherwise surfaces to the client as an opaque 500, not the error message
  // the UI's toast wants to show.
  try {
    await resolveScaffolderApprovalRPC({
      workflowId: gate.workflowId,
      approvalId,
      approved,
      approverId: uid,
      comment,
      workspaceId,
    })
  } catch (err) {
    return {
      ok: false,
      runId,
      errors: [err instanceof Error ? err.message : 'Failed to resolve the approval gate.'],
    }
  }

  return { ok: true, runId }
}

/** One `approval:request` step's gate info, for the run-detail page's UI. */
export interface ScaffolderApprovalGateInfo {
  approvalId: string
  message: string
  approvers: string[]
  /** Server-computed `canApproveScaffolderStep` result for the current viewer. */
  canApprove: boolean
}

/**
 * Loads every OPEN `approval:request` gate for a run, keyed by step id, for
 * {@link TemplateRunDetail} to render. Returns `{}` on any authorization or
 * lookup failure rather than throwing — a run-detail page that cannot
 * resolve gate info should still render the rest of the run (read-only), not
 * 500.
 */
export async function getScaffolderApprovalGates(
  runId: string,
): Promise<Record<string, ScaffolderApprovalGateInfo>> {
  const payload = await getPayload({ config })
  const user = await getCurrentUser()
  const uid = user?.id
  if (!uid) return {}
  const isAdmin = await currentUserIsPlatformAdmin()

  let run: ActionRun
  try {
    run = await payload.findByID({ collection: 'action-runs', id: runId, depth: 0, overrideAccess: true })
  } catch {
    return {}
  }
  const workspaceId = relId(run.workspace)
  if (!workspaceId || !run.workflowId) return {}
  if (!(await canRunTemplateDefinition(payload, uid, workspaceId, isAdmin))) return {}

  // By `runId` (this root run's action-runs doc id), not `workflowId` — see
  // the identical comment in `resolveScaffolderApproval` above. A gate
  // opened inside a `fetch:template`-nested child carries the CHILD's real
  // workflow id, not this root run's `run.workflowId`, but always carries
  // the root's `runId`.
  const gates = await payload.find({
    collection: 'pending-approvals',
    where: {
      and: [{ runId: { equals: runId } }, { status: { equals: 'pending' } }],
    },
    limit: 50,
    depth: 0,
    overrideAccess: true,
  })

  const out: Record<string, ScaffolderApprovalGateInfo> = {}
  for (const gate of gates.docs) {
    const gatePayload =
      gate.payload && typeof gate.payload === 'object' && !Array.isArray(gate.payload)
        ? (gate.payload as { message?: unknown; approvers?: unknown; stepId?: unknown })
        : {}
    const stepId = typeof gatePayload.stepId === 'string' ? gatePayload.stepId : null
    if (!stepId) continue

    const approvers = Array.isArray(gatePayload.approvers)
      ? gatePayload.approvers.filter((a): a is string => typeof a === 'string')
      : []
    const canApprove = await canApproveScaffolderStep(payload, uid, user?.email, workspaceId, approvers, isAdmin)

    out[stepId] = {
      approvalId: gate.approvalId,
      message: typeof gatePayload.message === 'string' ? gatePayload.message : gate.title,
      approvers,
      canApprove,
    }
  }
  return out
}
