// Package types provides shared types for workflows
package types

// TemplateInstantiationInput contains all parameters needed for template instantiation
type TemplateInstantiationInput struct {
	TemplateID       string            `json:"templateId"`       // ID of the template being instantiated
	WorkspaceID      string            `json:"workspaceId"`      // Workspace where repo will be created
	TargetOrg        string            `json:"targetOrg"`        // GitHub org/user for the new repo
	RepositoryName   string            `json:"repositoryName"`   // Name for the new repository
	Description      string            `json:"description"`      // Description for the new repository
	IsPrivate        bool              `json:"isPrivate"`        // Whether the repo should be private
	IsGitHubTemplate bool              `json:"isGitHubTemplate"` // True if template repo has GitHub template enabled
	SourceRepoOwner  string            `json:"sourceRepoOwner"`  // Owner of the source template repo
	SourceRepoName   string            `json:"sourceRepoName"`   // Name of the source template repo
	SourceRepoURL    string            `json:"sourceRepoUrl"`    // Full URL of source repo (for non-GitHub templates)
	Variables        map[string]string `json:"variables"`        // Template variables to substitute
	UserID           string            `json:"userId"`           // ID of user initiating instantiation
	InstallationID   string            `json:"installationId"`   // GitHub App installation ID for authentication
}

// TemplateInstantiationResult contains the workflow result
type TemplateInstantiationResult struct {
	Status   string // "completed", "failed"
	RepoURL  string // URL of the created repository
	RepoName string // Name of the created repository
	Error    string // Error message if failed
}

// InstantiationProgress tracks workflow progress for query handler
type InstantiationProgress struct {
	CurrentStep  string
	StepsTotal   int
	StepsCurrent int
	Message      string
}

// DeploymentWorkflowInput contains all parameters for deployment
type DeploymentWorkflowInput struct {
	DeploymentID  string                `json:"deploymentId"`
	AppID         string                `json:"appId"`
	WorkspaceID   string                `json:"workspaceId"`
	UserID        string                `json:"userId"`
	GeneratorType string                `json:"generatorType"`
	GeneratorSlug string                `json:"generatorSlug"`
	Config        []byte                `json:"config"`
	Target        DeploymentTargetInput `json:"target"`
	Mode          string                `json:"mode"` // "generate" or "execute", defaults to "execute"
}

// DeploymentTargetInput contains deployment target information
type DeploymentTargetInput struct {
	Type    string `json:"type"`
	Region  string `json:"region,omitempty"`
	Cluster string `json:"cluster,omitempty"`
	HostURL string `json:"hostUrl,omitempty"`
}

// GeneratedFile represents a file generated by a deployment
type GeneratedFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// DeploymentProgress tracks deployment workflow progress
type DeploymentProgress struct {
	CurrentStep    string          `json:"currentStep"`
	StepsTotal     int             `json:"stepsTotal"`
	StepsCurrent   int             `json:"stepsCurrent"`
	Message        string          `json:"message"`
	GeneratedFiles []GeneratedFile `json:"generatedFiles,omitempty"`
}
